package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;

import java.util.List;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService<Users> implements ApiService {

    private List<User> users = generateUsers();


    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        //je retourne la liste des Utilisateurs avec la variables users instancié plus haut
               return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
        public void generateRandomUser() {
               User randomUser = User.random();
               users.add(randomUser);
        /**je crée une variable randomUser qui, avec la fonction User.random(), génère un nom d'utilisateur de façon aléatoire
         *et j'ajoute cet utilisateur à la liste des utilisateurs retournée dans la fonction getUsers
         */
    }


    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        users.remove(user);
        //je supprime un utilisateur, de la nouvelle liste des utilisateurs mise à jour, grâce à la fonction .remove

    }
}





